// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBh5t2S51xo1XaUkZAhINxxDoRma06XxdI',
    appId: '1:448665014220:web:b825682de1f7c407035769',
    messagingSenderId: '448665014220',
    projectId: 'queensgambit-12ae9',
    authDomain: 'queensgambit-12ae9.firebaseapp.com',
    storageBucket: 'queensgambit-12ae9.firebasestorage.app',
    measurementId: 'G-WZP2TETZDN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwm4HyjjkquEXZdCGh2fLF1fOL7C9ezY8',
    appId: '1:448665014220:android:b0ea99340a065f38035769',
    messagingSenderId: '448665014220',
    projectId: 'queensgambit-12ae9',
    storageBucket: 'queensgambit-12ae9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCL3iKwdYHLaKY3Ab96-1-vBTHxVcBXRM',
    appId: '1:448665014220:ios:bc86944c66617327035769',
    messagingSenderId: '448665014220',
    projectId: 'queensgambit-12ae9',
    storageBucket: 'queensgambit-12ae9.firebasestorage.app',
    iosBundleId: 'com.example.queensGambit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCL3iKwdYHLaKY3Ab96-1-vBTHxVcBXRM',
    appId: '1:448665014220:ios:bc86944c66617327035769',
    messagingSenderId: '448665014220',
    projectId: 'queensgambit-12ae9',
    storageBucket: 'queensgambit-12ae9.firebasestorage.app',
    iosBundleId: 'com.example.queensGambit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBh5t2S51xo1XaUkZAhINxxDoRma06XxdI',
    appId: '1:448665014220:web:1b07b1c8df9a278f035769',
    messagingSenderId: '448665014220',
    projectId: 'queensgambit-12ae9',
    authDomain: 'queensgambit-12ae9.firebaseapp.com',
    storageBucket: 'queensgambit-12ae9.firebasestorage.app',
    measurementId: 'G-81B6Q3QP7Q',
  );
}
